title:              Putri Nabillah Blog
url:                "https://github.com/putrinabila20/putrinabila20.github.io"
email:              putrinabillahh212@gmail.com
description:        Hello guys my name is putri
author:             Putri Nabillah
baseurl:            "/startbootstrap-clean-blog-jekyll"

# Social Profiles
twitter_username:   putrinabila
github_username:    putrinabila20
facebook_username:  putrinabila
instagram_username: putrinabiillaa
linkedin_username: putrinabila

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
